"use client";
import Image from "next/image";import Link from "next/link";import { ArrowRight,Check,ChevronRight,Heart,MessageCircle,Search,ShieldCheck,Sparkles,Truck } from "lucide-react";import { useMemo,useState } from "react";import type { Product,SiteSettings } from "@/lib/store";import Header from "./Header";import CookieBanner from "./CookieBanner";import QuoteForm from "./QuoteForm";import ProductVisual from "./ProductVisual";
const categories=[['Termos & Mataralar','bottle','#295c50'],['İş Elbiseleri','vest','#e86d3e'],['Defter & Ajandalar','notebook','#c96e46'],['Bez & Sırt Çantaları','bag','#d4b88b'],['Matbaa Ürünleri','print','#315c50'],['Kurumsal Tekstil','shirt','#213c54']] as const;
const trend=['Teknolojik Ürünler','Bütçe Dostu Ürünler','Fuar & Etkinlik Ürünleri','Welcome Kit Önerileri','Premium Kurumsal Hediyeler','Sürdürülebilir Ürünler'];
export default function CatalogHome({initialProducts,settings}:{initialProducts:Product[];settings:SiteSettings}){const [query,setQuery]=useState('');const [list,setList]=useState<string[]>([]);const filtered=useMemo(()=>initialProducts.filter(p=>(p.name+' '+p.id+' '+p.category).toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr'))),[query,initialProducts]);const toggle=(id:string)=>setList(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]);return <><Header quoteCount={list.length}/><main>
<section className="catalog-hero"><Image src="/hero-products.png" fill priority sizes="100vw" alt="Kurumsal promosyon ürünleri, tekstil ve matbaa ürünleri"/><div className="catalog-hero-overlay"/><div className="catalog-container hero-copy"><p>Promosyon • Matbaa • İş Elbiseleri</p><h1>{settings.heroTitle}<br/><strong>{settings.heroAccent}</strong></h1><span>{settings.heroDescription}</span><form className="search-box" onSubmit={e=>e.preventDefault()} role="search"><label className="sr-only" htmlFor="product-search">Ürün ara</label><input id="product-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ürün, kategori veya ürün kodu ara"/><button aria-label="Ara"><Search/></button></form><div className="quick"><b>Sık arananlar:</b>{['Termos','Defter','Kalem','Çanta','İş Yeleği'].map(x=><button key={x} onClick={()=>setQuery(x)}>{x}</button>)}</div><div className="hero-benefits"><span><ShieldCheck/> Kaliteli baskı</span><span><Sparkles/> Tasarım desteği</span><span><Truck/> Hızlı teslimat</span></div></div></section>
<section className="catalog-section category-section"><div className="catalog-container"><Heading title="Popüler kategoriler"/><div className="category-row">{categories.map(([name,type,color])=><a className="category-card" key={name} href="#urunler"><ProductVisual type={type} color={color}/><strong>{name}</strong></a>)}</div></div></section>
<section className="sector-banner"><div className="catalog-container sector-inner"><div><small>SEKTÖRÜNÜZE ÖZEL</small><h2>Doğru promosyonu<br/><b>birlikte bulalım.</b></h2><p>İhtiyacınıza ve hedef kitlenize uygun ürünleri seçin.</p><a href="#teklif">Sektörünü seç <ArrowRight/></a></div><div className="sector-cards"><article><span>Teknoloji</span></article><article><span>Sağlık</span></article><article><span>İnşaat & Emlak</span></article></div></div></section>
<ProductShelf title={query?'Arama sonuçları':'Çok Satanlar'} items={filtered} list={list} toggle={toggle}/>
<section className="catalog-section ideas"><div className="catalog-container"><Heading title="En çok aranan koleksiyonlar"/><div className="idea-grid">{trend.map((x,i)=><a href="#urunler" key={x} className={`idea i${i}`}><span>{x}</span><ArrowRight/></a>)}</div></div></section>
<ProductShelf title="Yeni Gelenler" items={[...initialProducts].reverse()} list={list} toggle={toggle}/>
<section className="catalog-section quote-area" id="teklif"><div className="catalog-container quote-layout"><div><small>HIZLI TEKLİF</small><h2>Listeniz hazır,<br/>şimdi sıra bizde.</h2><p>{list.length?`${list.length} ürünü teklif listenize eklediniz. Adet ve baskı seçenekleri için formu gönderin.`:'Beğendiğiniz ürünleri teklif listenize ekleyin veya projenizi doğrudan anlatın.'}</p>{list.length>0&&<div className="selected-list">{list.map(id=><span key={id}>{id}<button onClick={()=>toggle(id)} aria-label={`${id} ürününü çıkar`}>×</button></span>)}</div>}</div><QuoteForm/></div></section>
</main><footer className="catalog-footer"><div className="catalog-container footer-grid"><div><b className="footer-logo">Meday</b><p>Promosyon, matbaa ve iş elbiselerinde kurumsal çözüm ortağınız.</p></div><div><strong>Ürünler</strong><a href="#urunler">Promosyon</a><a href="#urunler">Matbaa</a><a href="#urunler">İş elbiseleri</a></div><div><strong>Kurumsal</strong><Link href="/gizlilik">Gizlilik Politikası</Link><Link href="/kullanim-sartlari">Kullanım Şartları</Link></div><div><strong>Bize ulaşın</strong><a href={`tel:${settings.phone.replace(/\s/g,'')}`}>{settings.phone}</a><a href={`mailto:${settings.email}`}>{settings.email}</a></div></div><div className="catalog-container footer-copy">© {new Date().getFullYear()} {settings.businessName}</div></footer><a className="whatsapp" href={`https://wa.me/${settings.whatsapp}`} target="_blank" rel="noreferrer" aria-label="WhatsApp ile iletişime geç"><MessageCircle/><span><b>WhatsApp Destek</b><small>Size nasıl yardımcı olabiliriz?</small></span></a><CookieBanner/></>}
function Heading({title}:{title:string}){return <div className="catalog-heading"><h2>{title}</h2><a href="#urunler">Tümünü gör <ChevronRight/></a></div>}
function ProductShelf({title,items,list,toggle}:{title:string;items:Product[];list:string[];toggle:(id:string)=>void}){return <section className="catalog-section shelf" id="urunler"><div className="catalog-container"><Heading title={title}/>{items.length?<div className="product-row">{items.map(p=><article className="shop-card" key={p.id}><button className="heart" aria-label="Favoriye ekle"><Heart/></button><span className="product-badge">{p.badge}</span><Link className="product-detail-link" href={`/urunler/${encodeURIComponent(p.id)}`} aria-label={`${p.name} detaylarını görüntüle`}><ProductVisual type={p.type} color={p.color} imageUrl={p.imageUrls?.[0]||p.imageUrl} alt={p.name}/></Link><small>{p.id}</small><h3><Link href={`/urunler/${encodeURIComponent(p.id)}`}>{p.name}</Link></h3><p>Fiyat listesi aralığı</p><div className="prices"><s>{p.old}</s><b>{p.price}</b></div><div className="min"><span>Min. sipariş</span><b>{p.min} adet</b></div><button className={list.includes(p.id)?'add added':'add'} onClick={()=>toggle(p.id)}>{list.includes(p.id)?<><Check/> Listeye eklendi</>:'Teklif listesine ekle'}</button></article>)}</div>:<div className="empty-search"><Search/><h3>Aramanıza uygun ürün bulunamadı</h3></div>}</div></section>}
